trigger:
  branches:
    include:
      - main  # Replace with your main branch name

pool:
  vmImage: 'ubuntu-latest'  # Use the desired Azure VM image

steps:
  - script: 'pip install selenium webdriver_manager'  # Install required Python packages
    displayName: 'Install Python Dependencies'
  
  - script: 'python test_firstest.py'  # Run the Python script
    displayName: 'Run Selenium Test on LambdaTest'
